name: cmip6-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - python<3.12
  - numpy
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - xhistogram
  - numba>=0.58.0
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - globus-compute-endpoint
  - gcsfs
  - act-atmos
  - seaborn
  - esgf-pyclient
  - hvplot
  - holoviews
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - globus-compute-sdk
  - mystmd
  - ipywidgets
  - pip
  - sphinx-pythia-theme
  - ipywidgets
  - pip:
      - git+https://github.com/nocollier/intake-esgf
