name: cmip6-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - python<3.10
  - numpy
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - xhistogram
  - numba
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - seaborn
  