name: cmip6-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - python
  - numpy<1.24.0
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - xhistogram
  - numba
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - act-atmos
  - seaborn
  - esgf-pyclient
  - hvplot
  - holoviews
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - pip:
      - sphinx-pythia-theme
