name: cmip6-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - python
  - numpy!=1.23.1
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - xhistogram
  - numba
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - seaborn
  - pyesgf
  - hvplot
  - holoviews
