name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  build:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: cmip6-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'true'

  link-check:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      environment_name: cmip6-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'true'
