name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
      ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

  link-check:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
